# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/focal64"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.57.10"
    node1.vm.provider "virtualbox" do |vb|
        vb.name = "node1-linux-001-1"
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end
